Repository DevKor-github/team-c-back, pull requests merged in 2024-09, with the labels that each got.

#61 운영시간 수정
  src/main/java/devkor/com/teamcback/domain/building/entity/Building.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/entity/OperatingCondition.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/repositoy/OperatingConditionRepository.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
  src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
  src/main/java/devkor/com/teamcback/domain/place/entity/PlaceType.java
  src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingDetailRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceDetailRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomDetailRes.java
Labels: fix

#62 Fix: 정적 변수 제거
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
Labels: fix

#64 Fix/operatingtime 쉬는 시간 고려하도록 수정
  src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
  src/main/java/devkor/com/teamcback/domain/suggestion/entity/SuggestionType.java
  src/main/java/devkor/com/teamcback/global/response/ResultCode.java
Labels: fix

#63 Feat: 고연전 여부 API & 마이페이지 API 구현
  src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryRepository.java
  src/main/java/devkor/com/teamcback/domain/oauth2/service/OAuth2Service.java
  src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java
  src/main/java/devkor/com/teamcback/domain/search/entity/Koyeon.java
  src/main/java/devkor/com/teamcback/domain/search/repository/KoyeonRepository.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
  src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java
  src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java
  src/main/java/devkor/com/teamcback/domain/user/entity/Level.java
  src/main/java/devkor/com/teamcback/domain/user/entity/User.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
  src/main/java/devkor/com/teamcback/global/response/ResultCode.java
Labels: feat

#65 Feat: Place에 리뷰 평점, 이미지, 세부정보 추가
  src/main/java/devkor/com/teamcback/domain/place/dto/request/CreatePlaceReq.java
  src/main/java/devkor/com/teamcback/domain/place/dto/request/ModifyPlaceReq.java
  src/main/java/devkor/com/teamcback/domain/place/dto/response/GetPlaceRes.java
  src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
  src/main/java/devkor/com/teamcback/domain/place/entity/PlaceImage.java
  src/main/java/devkor/com/teamcback/domain/place/repository/PlaceImageRepository.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityTypeRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceDetailRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceImageRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomDetailRes.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Labels: feat

#66 User 관련 기능 추가 및 수정
  src/main/java/devkor/com/teamcback/domain/oauth2/service/OAuth2Service.java
  src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java
  src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java
  src/main/java/devkor/com/teamcback/domain/user/dto/response/ModifyUsernameRes.java
  src/main/java/devkor/com/teamcback/domain/user/entity/Level.java
  src/main/java/devkor/com/teamcback/domain/user/entity/ProfileImage.java
  src/main/java/devkor/com/teamcback/domain/user/entity/User.java
  src/main/java/devkor/com/teamcback/domain/user/repository/UserRepository.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
  src/main/java/devkor/com/teamcback/global/response/ResultCode.java
Labels: fix, feat

#73 FE와 로그인 통합, 검색 로그 수정
  src/main/java/devkor/com/teamcback/domain/oauth2/dto/OAuth2UserInfo.java
  src/main/java/devkor/com/teamcback/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/devkor/com/teamcback/domain/oauth2/service/OAuth2Service.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/HolidayService.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
  src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java
  src/main/java/devkor/com/teamcback/domain/user/dto/request/LoginUserReq.java
  src/main/java/devkor/com/teamcback/domain/user/entity/User.java
  src/main/java/devkor/com/teamcback/domain/user/repository/UserRepository.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
  src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java
  src/main/java/devkor/com/teamcback/global/jwt/JwtUtil.java
  src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
  src/main/java/devkor/com/teamcback/global/security/UserDetailsServiceImpl.java
  src/main/java/devkor/com/teamcback/global/security/logout/LogoutSuccessHandlerImpl.java
  src/main/resources/application.yml
Labels: fix

#75 Operating time 시간 타입 변경
  src/main/java/devkor/com/teamcback/domain/operatingtime/entity/OperatingTime.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
  src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
Labels: fix

#76 운영시간 코드 리팩토링
  src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
  src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
Labels: refactor

#78 Fix: 건물 다음 운영 시간을 찾는 로직 오류 수정
  src/main/java/devkor/com/teamcback/domain/operatingtime/entity/DayOfWeek.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/HolidayScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/OperatingScheduler.java
  src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
  src/main/java/devkor/com/teamcback/domain/routes/entity/NodeType.java
Labels: fix

#81 Feat: 출입구, 계단, 엘베 정보도 반환
  src/main/java/devkor/com/teamcback/domain/routes/repository/NodeRepository.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchNodeRes.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomRes.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Labels: feat

#83 카테고리 및 즐겨찾기 수정
  src/main/java/devkor/com/teamcback/domain/bookmark/controller/BookmarkController.java
  src/main/java/devkor/com/teamcback/domain/bookmark/controller/CategoryController.java
  src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/CreateBookmarkReq.java
  src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/CreateBookmarkRes.java
  src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetCategoryListRes.java
  src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetCategoryRes.java
  src/main/java/devkor/com/teamcback/domain/bookmark/entity/Bookmark.java
  src/main/java/devkor/com/teamcback/domain/bookmark/entity/Category.java
  src/main/java/devkor/com/teamcback/domain/bookmark/entity/CategoryBookmark.java
  src/main/java/devkor/com/teamcback/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryBookmarkRepository.java
  src/main/java/devkor/com/teamcback/domain/bookmark/service/BookmarkService.java
  src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java
  src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFloorInfoRes.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Labels: fix

#84 Fix: SearchLog 및 dto 수정
  src/main/java/devkor/com/teamcback/domain/search/dto/request/SaveSearchLogReq.java
  src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchLogRes.java
  src/main/java/devkor/com/teamcback/domain/search/entity/SearchLog.java
  src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Labels: fix

#85 Fix: 카테고리 조회 파라미터 required=false 추가
  src/main/java/devkor/com/teamcback/domain/bookmark/controller/CategoryController.java
Labels: fix

#86 Fix: 토큰을 userId로 발급하도록 수정
  src/main/java/devkor/com/teamcback/domain/user/repository/UserRepository.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
  src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java
  src/main/java/devkor/com/teamcback/global/jwt/JwtUtil.java
  src/main/java/devkor/com/teamcback/global/security/UserDetailsServiceImpl.java
Labels: fix

#89 Fix: refreshToken 오류 수정
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
Labels: !HOTFIX

#94 Feat: 기본 카테고리 자동 저장 추가
  src/main/java/devkor/com/teamcback/domain/bookmark/entity/Category.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
Labels: feat

#96 마이페이지 응답에 레벨 관련 필드 추가
  src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java
  src/main/java/devkor/com/teamcback/domain/user/entity/Level.java
  src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
Labels: feat

#107 Feat: 태그검색 API
  src/main/java/devkor/com/teamcback/domain/koyeon/controller/KoyeonController.java
  src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubRes.java
  src/main/java/devkor/com/teamcback/domain/koyeon/repository/MenuRepository.java
  src/main/java/devkor/com/teamcback/domain/koyeon/repository/TagMenuRepository.java
  src/main/java/devkor/com/teamcback/domain/koyeon/service/KoyeonService.java
  src/main/java/devkor/com/teamcback/global/response/ResultCode.java
Labels: feat
